# Generated by Django 3.1.7 on 2021-03-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eadditives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eadditives',
            name='description',
            field=models.TextField(blank=True, default=True, null=True),
        ),
    ]
